<?php

return array(
	'ticketStatus' => array(
		'new'     => 'New',
		'open'    => 'Open',
		'enroute' => 'Enroute',
		'on_site' => 'On Site',
		'close'   => 'Close',
	),
	'dashboardTitle' => array(
		'5' => 'Responder HQ Dashboard',
		'3' => 'Dispatcher HQ Dashboard',
		'6' => "Mayor's Dashboard",
	),
	'months' => array(
		'all'  => 'All Time',
		'1'  => 'January',
		'2'  => 'February',
		'3'  => 'March',
		'4'  => 'April',
		'5'  => 'May',
		'6'  => 'June',
		'7' => 'July',
		'8'  => 'August',
		'9' => 'September',
		'10'  => 'October',
		'11'  => 'November',
		'12'  => 'December',
	),
	'allowedVideos' => array(
		'video/x-ms-asf',
		'video/x-ms-wmv',
		'video/x-ms-wmx',
		'video/x-ms-wm',
		'video/avi',
		'video/divx',
		'video/x-flv',
		'video/quicktime',
		'video/mpeg',
		'video/mp4',
		'video/ogg',
		'video/webm',
		'video/x-matroska',
	),
	'allowedImages' => array(
		'image/gif',
		'image/jpeg',
		'image/png',
		'image/bmp',
		'image/svg+xml',
		'image/tiff',
		'image/gif',
	),
);